[package]
name = "ksr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
core-foundation = "0.9.3"
core-graphics = "0.22.3"
dirs = "4.0.0"
libc = "0.2.139"

[build-dependencies]
cc = "1.0.79"

